// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atkpaswofahpmxpfiujb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0a3Bhc3dvZmFocG14cGZpdWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU2MjIxODMsImV4cCI6MjA1MTE5ODE4M30.VYxnqkQZ3eftv7QcRSmVHkYUl3PnBakensKBRrzMMz8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);